config/routes.rb
Rails.application.routes.draw do

  get 'rooms/create'
  get 'rooms/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as:'about'
  get '/search' => 'searches#search'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'followings' => 'relationships#followings', as: 'followings'
  end
  resources :books do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  resources :messages, only:[:create]
  resources :rooms, only:[:create,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(seachwords,hows)
    if hows == "match"
      @book = Book.where("title LIKE ?","#{seachwords}")
    elsif hows == "forward_match"
      @book = Book.where("title LIKE ?","#{seachwords}%")
    elsif hows == "backward_match"
      @book = Book.where("title LIKE ?","%#{seachwords}")
    else
      @book = Book.where("title LIKE ?","%#{seachwords}%")
    end
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship",foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  attachment :profile_image

  validates :name, uniqueness: true, length: { in:2..20 }
  validates :introduction, length: { maximum: 50 }
  
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
   followings.include?(user)
  end

  def self.looks(seachwords,hows)
    if hows == "match"
      @user = User.where("name LIKE ?","#{seachwords}")
    elsif hows == "forward_match"
      @user = User.where("name LIKE ?","#{seachwords}%")
    elsif hows == "backward_match"
      @user = User.where("name LIKE ?","%#{seachwords}")
    else
      @user = User.where("name LIKE ?","%#{seachwords}%")
    end
  end  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_user, only: [:edit, :update, :destroy]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @newbook = Book.new
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def index
    @user = current_user
    @book = Book.new
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b| 
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=> 
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_user
    @books = current_user.books
    @book = @books.find_by(id: params[:id])
    redirect_to books_path unless @book
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: users_path)
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_user, only: [:edit, :update]

  def show
    @newbook = Book.new
    @user = User.find(params[:id])
    @books = @user.books
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end    
  end

  def index
    @newbook = Book.new
    @user = current_user
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_user
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user)
    end
  end
  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>title</th>
      <th>opinion</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, size:"50x50", fallback:"no_image.jpg" %>
        <% end %>
      </td>
      <td>
        <%= link_to book_path(book.id) do %>
          <%= book.title %></td>
        <% end %>
      <td><%= book.body %></td>
      <td id="favorite-btn_<%= book.id %>">
        <%= render "favorites/favorite-btn",book: book %>
      </td>
      <td>コメント数：<%= book.book_comments.count %></td>
    </tr>
    <% end %>

</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class:'form-control'%>
        </div>
        <div class="form-group">
          <label>Body</label>
          <%= f.text_area :body, class:'form-control'%>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book',class:'btn btn-success' %>
        </div>
      <% end %>
      <%= link_to "Show", book_path %>
       | 
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
    <div id = "error_explanation">
      <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/sidebar', user: @user, book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/sidebar', user: @user, book: @newbook%>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, size:"40x40", fallback:"no_image.jpg" %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <td id="favorite-btn_<%= @book.id %>">
              <%= render "favorites/favorite-btn",book: @book %>
            </td>
            <td class="comment-count">コメント数：<%= @book.book_comments.count %></td>
            <% if @book.user == current_user %>
            <td>
              <%= link_to "Edit", edit_book_path(@book),class:' btn btn-sm btn-success' %>
            </td>
            <td>
              <%= link_to "Destroy",  book_path(@book), method: :delete,"data-confirm" => "本当に消しますか？",class:' btn btn-sm btn-danger'%>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table class="book_comment_area">
      <%= render "book_comments/book_comment", book: @book %>
      </table>
      <div>
        <%= form_with(model:[@book,@book_comment])do |f|%>
        <div>
        <%= f.text_area :comment, rows:'5',class:"form-control" %>
        </div>
        <div>
        <%= f.submit "送信",class:'mt-3'%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<p>チャット</p>

<% @entries.each do |e| %>
  <div class="user-name">
  <strong>
    <a><%= e.user.name %>さん</a>
  </strong>
  </div>
<% end %>
<hr>
<div class="chats">
  <div class="chat">
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <div class="chat-box">
          <div><strong><%= m.content %></strong></div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="posts">
    <%= form_for @message do |f| %>
      <%= f.text_field :content, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
        <%= f.hidden_field :room_id, value: @room.id %>
          <% f.submit %>
    <% end %>
  </div>
</div>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, size:"40x40", fallback:"no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.followings.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <% if current_user == user %>
        <td></td>
      <% else %>
        <% if current_user.following?(user) %>
          <td>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          </td>
        <% else %>
          <td>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          </td>
        <% end %>
      <% end %>
      <td>
        <%= link_to "Show", user_path(user)%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_sidebar.html.erb
<h2>User info</h2>
<%= attachment_image_tag user,:profile_image, size:"63x63",fallback:"no_image.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>
  </tbody>
</table>
<% unless user.id == current_user.id %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-sm btn-primary mb-3" %>
    <% if (current_user.following? user) && (user.following? current_user) %>
    <% if @isRoom == true %>
      <% link_to "Chatを始める", room_path(@roomId) %>
    <% else %>
      <%= form_for @room do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "Chatを始める" %>
      <% end %>
    <% end %>
    <% end %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-sm btn-success mb-3" %>
  <% end %>
<% end %>
<% if user == current_user %>
  <div class="row">
    <%= link_to '',edit_user_path(user.id), class:'btn btn-outline-secondary btn-block fas fa-user-cog' %>
  </div>
<% end %>


<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title,class:'form-control' %>
  </div>
  <div class="form-group">
    <label>Option</label>
    <%= f.text_area :body,class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book',class:'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2 class="mt-3">Users info</h2>

      <% if @user.errors.any? %>
        <div id = "error_explanation">
          <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name,autofocus: true, id:"user_name",placeholder:"name", class:'form-control' %>
        </div>
        <div class="form-group">
          <label for="profile_image">Image</label>
          <%= f.attachment_field :profile_image, placeholder:"profile_image", class:'form-control-file' %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, id:"user_introduction",placeholder:"introduction", class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User",class:'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/sidebar', user: @user, book: @newbook%>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/sidebar', user: @user, book: @newbook%>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>opinion</th>
            <th
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size:"40x40", fallback:"no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
      