config/routes.rb
Rails.application.routes.draw do

  get 'rooms/create'
  get 'rooms/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as:'about'
  get '/search' => 'searches#search'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'followings' => 'relationships#followings', as: 'followings'
  end
  resources :books do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  resources :messages, only:[:create]
  resources :rooms, only:[:create,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(seachwords,hows)
    if hows == "match"
      @book = Book.where("title LIKE ?","#{seachwords}")
    elsif hows == "forward_match"
      @book = Book.where("title LIKE ?","#{seachwords}%")
    elsif hows == "backward_match"
      @book = Book.where("title LIKE ?","%#{seachwords}")
    else
      @book = Book.where("title LIKE ?","%#{seachwords}%")
    end
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship",foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  attachment :profile_image

  validates :name, uniqueness: true, length: { in:2..20 }
  validates :introduction, length: { maximum: 50 }
  
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
   followings.include?(user)
  end

  def self.looks(seachwords,hows)
    if hows == "match"
      @user = User.where("name LIKE ?","#{seachwords}")
    elsif hows == "forward_match"
      @user = User.where("name LIKE ?","#{seachwords}%")
    elsif hows == "backward_match"
      @user = User.where("name LIKE ?","%#{seachwords}")
    else
      @user = User.where("name LIKE ?","%#{seachwords}%")
    end
  end  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_user, only: [:edit, :update, :destroy]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @newbook = Book.new
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def index
    @user = current_user
    @book = Book.new
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b| 
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=> 
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_user
    @books = current_user.books
    @book = @books.find_by(id: params[:id])
    redirect_to books_path unless @book
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: users_path)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/942cb3814e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
    <header>
      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers",root_path, class:'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to "Home", user_path(current_user.id), class:'fas fa-home nav-link text-light' %>
              </li>
              <li>
                <%= link_to "Users", users_path, class:'fas fa-users nav-link text-light' %>
              </li>
              <li>
                <%= link_to "Books", books_path, class:'fas fa-book-open nav-link text-light' %>
              </li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class:'fas fa-sign-out-alt nav-link text-light' %>
              </li>
              <% else %>
              <li>
                <%= link_to "Home", root_path, class:'fas fa-home nav-link text-light' %>
              </li>
              <li>
                <%= link_to "About", about_path, class:'fas fa-link nav-link text-light' %>
              </li>
              <li>
                <%= link_to "Sign up", new_user_registration_path, class:'fas fa-user-plus nav-link text-light' %>
              </li>
              <li>
                <%= link_to "Log in", new_user_session_path, class:'fas fa-sign-in-alt nav-link text-light' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
      <div class="container mt-3">
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3 text-center mx-auto">
            <% if user_signed_in? %>
              <%= form_with url: search_path, method: :get, local:true do |f| %>
                <%= f.text_field :searchword %>
                <%= f.select :range, options_for_select([["User"],["Book"]]) %>
                <%= f.select :how, options_for_select([["完全一致","match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partical_match"]]) %>
                <%= f.submit '検索' %>
              <% end %>
            <% end %>
          </div>
        </div>  
      </div>
    <%= yield %>
    </main>
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>